[package]
name = "secret-clan"
version = "0.1.0"
authors = ["Florian Richter <floririchte@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4.11"
flexi_logger = "0.16.2"
tokio = { version = "0.2.23", features = ["full"] }
warp = "0.2.5"
time = "0.2.23"
nanoid = "0.3.0"
httparse = "1.3.4"
envconfig = "0.9.1"
serde = "1.0.117"
serde_json = "1.0.59"
serde_urlencoded = "0.7.0"
serde_derive = "1.0.117"
