name: Build, Lint and Test
on: push
jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: Lint
        run: cargo clippy
      - name: Test
        run: cargo test
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Fetch Dependencies
        run: npm install
      - name: Check Dependencies
        run: npm audit
      - name: Build
        run: npm run build:prod
      - name: Lint
        run: npm run lint
