name: Build, Lint and Test
on: push
jobs:
  backend:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd backend
      - name: Build
        run: cargo build --release
      - name: Lint
        run: cargo clippy
  frontend:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - run: cd frontend
      - name: Fetch Dependencies
        run: yarn
      - name: Check Dependencies
        run: yarn audit --groups dependencies
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
