name: Build, Lint, Audit and Test
on: push
jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.16.0"
          args: "-r backend"
      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Fetch Dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Lint
        run: npm run lint
      - name: Audit
        run: npm audit
