name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Build Image
        run: docker build -t secret-clan .
      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-central-1
      - name: Push to ECR
        run: |
          docker tag secret-clan:latest ${{ steps.ecr.outputs.account }}.dkr.ecr.eu-central-1.amazonaws.com/secret-clan:latest
          docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.eu-central-1.amazonaws.com/secret-clan:latest
