// This file is generated by rust-protobuf 2.20.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `card.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_20_0;

#[derive(PartialEq,Clone,Default)]
pub struct Card {
    // message fields
    pub color: Card_Color,
    pub value: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Card {
    fn default() -> &'a Card {
        <Card as ::protobuf::Message>::default_instance()
    }
}

impl Card {
    pub fn new() -> Card {
        ::std::default::Default::default()
    }

    // .Card.Color color = 1;


    pub fn get_color(&self) -> Card_Color {
        self.color
    }
    pub fn clear_color(&mut self) {
        self.color = Card_Color::HEARTS;
    }

    // Param is passed by value, moved
    pub fn set_color(&mut self, v: Card_Color) {
        self.color = v;
    }

    // uint32 value = 2;


    pub fn get_value(&self) -> u32 {
        self.value
    }
    pub fn clear_value(&mut self) {
        self.value = 0;
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: u32) {
        self.value = v;
    }
}

impl ::protobuf::Message for Card {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.color, 1, &mut self.unknown_fields)?
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.value = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.color != Card_Color::HEARTS {
            my_size += ::protobuf::rt::enum_size(1, self.color);
        }
        if self.value != 0 {
            my_size += ::protobuf::rt::value_size(2, self.value, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.color != Card_Color::HEARTS {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.color))?;
        }
        if self.value != 0 {
            os.write_uint32(2, self.value)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Card {
        Card::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Card_Color>>(
                "color",
                |m: &Card| { &m.color },
                |m: &mut Card| { &mut m.color },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "value",
                |m: &Card| { &m.value },
                |m: &mut Card| { &mut m.value },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Card>(
                "Card",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Card {
        static instance: ::protobuf::rt::LazyV2<Card> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Card::new)
    }
}

impl ::protobuf::Clear for Card {
    fn clear(&mut self) {
        self.color = Card_Color::HEARTS;
        self.value = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Card {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Card {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Card_Color {
    HEARTS = 0,
    TILES = 1,
    CLOVERS = 2,
    PIKES = 3,
}

impl ::protobuf::ProtobufEnum for Card_Color {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Card_Color> {
        match value {
            0 => ::std::option::Option::Some(Card_Color::HEARTS),
            1 => ::std::option::Option::Some(Card_Color::TILES),
            2 => ::std::option::Option::Some(Card_Color::CLOVERS),
            3 => ::std::option::Option::Some(Card_Color::PIKES),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Card_Color] = &[
            Card_Color::HEARTS,
            Card_Color::TILES,
            Card_Color::CLOVERS,
            Card_Color::PIKES,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<Card_Color>("Card.Color", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for Card_Color {
}

impl ::std::default::Default for Card_Color {
    fn default() -> Self {
        Card_Color::HEARTS
    }
}

impl ::protobuf::reflect::ProtobufValue for Card_Color {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\ncard.proto\"w\n\x04Card\x12!\n\x05color\x18\x01\x20\x01(\x0e2\x0b.Ca\
    rd.ColorR\x05color\x12\x14\n\x05value\x18\x02\x20\x01(\rR\x05value\"6\n\
    \x05Color\x12\n\n\x06HEARTS\x10\0\x12\t\n\x05TILES\x10\x01\x12\x0b\n\x07\
    CLOVERS\x10\x02\x12\t\n\x05PIKES\x10\x03J\xf0\x02\n\x06\x12\x04\0\0\x0b\
    \x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0\x0b\
    \x01\n\n\n\x03\x04\0\x01\x12\x03\x02\x08\x0c\n\x0c\n\x04\x04\0\x04\0\x12\
    \x04\x03\x02\x08\x03\n\x0c\n\x05\x04\0\x04\0\x01\x12\x03\x03\x07\x0c\n\r\
    \n\x06\x04\0\x04\0\x02\0\x12\x03\x04\x04\x0f\n\x0e\n\x07\x04\0\x04\0\x02\
    \0\x01\x12\x03\x04\x04\n\n\x0e\n\x07\x04\0\x04\0\x02\0\x02\x12\x03\x04\r\
    \x0e\n\r\n\x06\x04\0\x04\0\x02\x01\x12\x03\x05\x04\x0e\n\x0e\n\x07\x04\0\
    \x04\0\x02\x01\x01\x12\x03\x05\x04\t\n\x0e\n\x07\x04\0\x04\0\x02\x01\x02\
    \x12\x03\x05\x0c\r\n\r\n\x06\x04\0\x04\0\x02\x02\x12\x03\x06\x04\x10\n\
    \x0e\n\x07\x04\0\x04\0\x02\x02\x01\x12\x03\x06\x04\x0b\n\x0e\n\x07\x04\0\
    \x04\0\x02\x02\x02\x12\x03\x06\x0e\x0f\n\r\n\x06\x04\0\x04\0\x02\x03\x12\
    \x03\x07\x04\x0e\n\x0e\n\x07\x04\0\x04\0\x02\x03\x01\x12\x03\x07\x04\t\n\
    \x0e\n\x07\x04\0\x04\0\x02\x03\x02\x12\x03\x07\x0c\r\n\x0b\n\x04\x04\0\
    \x02\0\x12\x03\t\x02\x12\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\t\x02\x07\n\
    \x0c\n\x05\x04\0\x02\0\x01\x12\x03\t\x08\r\n\x0c\n\x05\x04\0\x02\0\x03\
    \x12\x03\t\x10\x11\n\x0b\n\x04\x04\0\x02\x01\x12\x03\n\x02\x13\n\x0c\n\
    \x05\x04\0\x02\x01\x05\x12\x03\n\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\
    \x12\x03\n\t\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\n\x11\x12b\x06pro\
    to3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
