// This file is generated by rust-protobuf 2.20.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `message.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_20_0;

#[derive(PartialEq,Clone,Default)]
pub struct Client {
    // message oneof groups
    pub message: ::std::option::Option<Client_oneof_message>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Client {
    fn default() -> &'a Client {
        <Client as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum Client_oneof_message {
    authConfirmed(Client_AuthConfirmed),
    nameUpdated(Client_NameUpdated),
    gameStarted(Client_GameStarted),
}

impl Client {
    pub fn new() -> Client {
        ::std::default::Default::default()
    }

    // .Client.AuthConfirmed authConfirmed = 1;


    pub fn get_authConfirmed(&self) -> &Client_AuthConfirmed {
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::authConfirmed(ref v)) => v,
            _ => <Client_AuthConfirmed as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_authConfirmed(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_authConfirmed(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::authConfirmed(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_authConfirmed(&mut self, v: Client_AuthConfirmed) {
        self.message = ::std::option::Option::Some(Client_oneof_message::authConfirmed(v))
    }

    // Mutable pointer to the field.
    pub fn mut_authConfirmed(&mut self) -> &mut Client_AuthConfirmed {
        if let ::std::option::Option::Some(Client_oneof_message::authConfirmed(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Client_oneof_message::authConfirmed(Client_AuthConfirmed::new()));
        }
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::authConfirmed(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_authConfirmed(&mut self) -> Client_AuthConfirmed {
        if self.has_authConfirmed() {
            match self.message.take() {
                ::std::option::Option::Some(Client_oneof_message::authConfirmed(v)) => v,
                _ => panic!(),
            }
        } else {
            Client_AuthConfirmed::new()
        }
    }

    // .Client.NameUpdated nameUpdated = 2;


    pub fn get_nameUpdated(&self) -> &Client_NameUpdated {
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::nameUpdated(ref v)) => v,
            _ => <Client_NameUpdated as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_nameUpdated(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_nameUpdated(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::nameUpdated(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_nameUpdated(&mut self, v: Client_NameUpdated) {
        self.message = ::std::option::Option::Some(Client_oneof_message::nameUpdated(v))
    }

    // Mutable pointer to the field.
    pub fn mut_nameUpdated(&mut self) -> &mut Client_NameUpdated {
        if let ::std::option::Option::Some(Client_oneof_message::nameUpdated(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Client_oneof_message::nameUpdated(Client_NameUpdated::new()));
        }
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::nameUpdated(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_nameUpdated(&mut self) -> Client_NameUpdated {
        if self.has_nameUpdated() {
            match self.message.take() {
                ::std::option::Option::Some(Client_oneof_message::nameUpdated(v)) => v,
                _ => panic!(),
            }
        } else {
            Client_NameUpdated::new()
        }
    }

    // .Client.GameStarted gameStarted = 3;


    pub fn get_gameStarted(&self) -> &Client_GameStarted {
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::gameStarted(ref v)) => v,
            _ => <Client_GameStarted as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_gameStarted(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_gameStarted(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::gameStarted(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_gameStarted(&mut self, v: Client_GameStarted) {
        self.message = ::std::option::Option::Some(Client_oneof_message::gameStarted(v))
    }

    // Mutable pointer to the field.
    pub fn mut_gameStarted(&mut self) -> &mut Client_GameStarted {
        if let ::std::option::Option::Some(Client_oneof_message::gameStarted(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Client_oneof_message::gameStarted(Client_GameStarted::new()));
        }
        match self.message {
            ::std::option::Option::Some(Client_oneof_message::gameStarted(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_gameStarted(&mut self) -> Client_GameStarted {
        if self.has_gameStarted() {
            match self.message.take() {
                ::std::option::Option::Some(Client_oneof_message::gameStarted(v)) => v,
                _ => panic!(),
            }
        } else {
            Client_GameStarted::new()
        }
    }
}

impl ::protobuf::Message for Client {
    fn is_initialized(&self) -> bool {
        if let Some(Client_oneof_message::authConfirmed(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Client_oneof_message::nameUpdated(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Client_oneof_message::gameStarted(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Client_oneof_message::authConfirmed(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Client_oneof_message::nameUpdated(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Client_oneof_message::gameStarted(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.message {
            match v {
                &Client_oneof_message::authConfirmed(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Client_oneof_message::nameUpdated(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Client_oneof_message::gameStarted(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.message {
            match v {
                &Client_oneof_message::authConfirmed(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Client_oneof_message::nameUpdated(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Client_oneof_message::gameStarted(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Client {
        Client::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Client_AuthConfirmed>(
                "authConfirmed",
                Client::has_authConfirmed,
                Client::get_authConfirmed,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Client_NameUpdated>(
                "nameUpdated",
                Client::has_nameUpdated,
                Client::get_nameUpdated,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Client_GameStarted>(
                "gameStarted",
                Client::has_gameStarted,
                Client::get_gameStarted,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Client>(
                "Client",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Client {
        static instance: ::protobuf::rt::LazyV2<Client> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Client::new)
    }
}

impl ::protobuf::Clear for Client {
    fn clear(&mut self) {
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Client {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Client {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Client_AuthConfirmed {
    // message fields
    pub token: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Client_AuthConfirmed {
    fn default() -> &'a Client_AuthConfirmed {
        <Client_AuthConfirmed as ::protobuf::Message>::default_instance()
    }
}

impl Client_AuthConfirmed {
    pub fn new() -> Client_AuthConfirmed {
        ::std::default::Default::default()
    }

    // string token = 1;


    pub fn get_token(&self) -> &str {
        &self.token
    }
    pub fn clear_token(&mut self) {
        self.token.clear();
    }

    // Param is passed by value, moved
    pub fn set_token(&mut self, v: ::std::string::String) {
        self.token = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_token(&mut self) -> &mut ::std::string::String {
        &mut self.token
    }

    // Take field
    pub fn take_token(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.token, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Client_AuthConfirmed {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.token)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.token.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.token.is_empty() {
            os.write_string(1, &self.token)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Client_AuthConfirmed {
        Client_AuthConfirmed::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "token",
                |m: &Client_AuthConfirmed| { &m.token },
                |m: &mut Client_AuthConfirmed| { &mut m.token },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Client_AuthConfirmed>(
                "Client.AuthConfirmed",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Client_AuthConfirmed {
        static instance: ::protobuf::rt::LazyV2<Client_AuthConfirmed> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Client_AuthConfirmed::new)
    }
}

impl ::protobuf::Clear for Client_AuthConfirmed {
    fn clear(&mut self) {
        self.token.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Client_AuthConfirmed {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Client_AuthConfirmed {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Client_NameUpdated {
    // message fields
    pub name: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Client_NameUpdated {
    fn default() -> &'a Client_NameUpdated {
        <Client_NameUpdated as ::protobuf::Message>::default_instance()
    }
}

impl Client_NameUpdated {
    pub fn new() -> Client_NameUpdated {
        ::std::default::Default::default()
    }

    // string name = 1;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Client_NameUpdated {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Client_NameUpdated {
        Client_NameUpdated::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &Client_NameUpdated| { &m.name },
                |m: &mut Client_NameUpdated| { &mut m.name },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Client_NameUpdated>(
                "Client.NameUpdated",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Client_NameUpdated {
        static instance: ::protobuf::rt::LazyV2<Client_NameUpdated> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Client_NameUpdated::new)
    }
}

impl ::protobuf::Clear for Client_NameUpdated {
    fn clear(&mut self) {
        self.name.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Client_NameUpdated {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Client_NameUpdated {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Client_GameStarted {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Client_GameStarted {
    fn default() -> &'a Client_GameStarted {
        <Client_GameStarted as ::protobuf::Message>::default_instance()
    }
}

impl Client_GameStarted {
    pub fn new() -> Client_GameStarted {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Client_GameStarted {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Client_GameStarted {
        Client_GameStarted::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Client_GameStarted>(
                "Client.GameStarted",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Client_GameStarted {
        static instance: ::protobuf::rt::LazyV2<Client_GameStarted> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Client_GameStarted::new)
    }
}

impl ::protobuf::Clear for Client_GameStarted {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Client_GameStarted {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Client_GameStarted {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server {
    // message oneof groups
    pub message: ::std::option::Option<Server_oneof_message>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server {
    fn default() -> &'a Server {
        <Server as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum Server_oneof_message {
    playerUpdated(Server_PlayerUpdated),
    gameUpdated(Server_GameUpdated),
    selfUpdated(Server_SelfUpdated),
    playerEntered(Server_PlayerEntered),
    playerLeft(Server_PlayerLeft),
    gameDeclined(Server_GameDeclined),
}

impl Server {
    pub fn new() -> Server {
        ::std::default::Default::default()
    }

    // .Server.PlayerUpdated playerUpdated = 1;


    pub fn get_playerUpdated(&self) -> &Server_PlayerUpdated {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerUpdated(ref v)) => v,
            _ => <Server_PlayerUpdated as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_playerUpdated(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_playerUpdated(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerUpdated(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_playerUpdated(&mut self, v: Server_PlayerUpdated) {
        self.message = ::std::option::Option::Some(Server_oneof_message::playerUpdated(v))
    }

    // Mutable pointer to the field.
    pub fn mut_playerUpdated(&mut self) -> &mut Server_PlayerUpdated {
        if let ::std::option::Option::Some(Server_oneof_message::playerUpdated(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Server_oneof_message::playerUpdated(Server_PlayerUpdated::new()));
        }
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerUpdated(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_playerUpdated(&mut self) -> Server_PlayerUpdated {
        if self.has_playerUpdated() {
            match self.message.take() {
                ::std::option::Option::Some(Server_oneof_message::playerUpdated(v)) => v,
                _ => panic!(),
            }
        } else {
            Server_PlayerUpdated::new()
        }
    }

    // .Server.GameUpdated gameUpdated = 2;


    pub fn get_gameUpdated(&self) -> &Server_GameUpdated {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::gameUpdated(ref v)) => v,
            _ => <Server_GameUpdated as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_gameUpdated(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_gameUpdated(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::gameUpdated(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_gameUpdated(&mut self, v: Server_GameUpdated) {
        self.message = ::std::option::Option::Some(Server_oneof_message::gameUpdated(v))
    }

    // Mutable pointer to the field.
    pub fn mut_gameUpdated(&mut self) -> &mut Server_GameUpdated {
        if let ::std::option::Option::Some(Server_oneof_message::gameUpdated(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Server_oneof_message::gameUpdated(Server_GameUpdated::new()));
        }
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::gameUpdated(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_gameUpdated(&mut self) -> Server_GameUpdated {
        if self.has_gameUpdated() {
            match self.message.take() {
                ::std::option::Option::Some(Server_oneof_message::gameUpdated(v)) => v,
                _ => panic!(),
            }
        } else {
            Server_GameUpdated::new()
        }
    }

    // .Server.SelfUpdated selfUpdated = 3;


    pub fn get_selfUpdated(&self) -> &Server_SelfUpdated {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::selfUpdated(ref v)) => v,
            _ => <Server_SelfUpdated as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_selfUpdated(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_selfUpdated(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::selfUpdated(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_selfUpdated(&mut self, v: Server_SelfUpdated) {
        self.message = ::std::option::Option::Some(Server_oneof_message::selfUpdated(v))
    }

    // Mutable pointer to the field.
    pub fn mut_selfUpdated(&mut self) -> &mut Server_SelfUpdated {
        if let ::std::option::Option::Some(Server_oneof_message::selfUpdated(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Server_oneof_message::selfUpdated(Server_SelfUpdated::new()));
        }
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::selfUpdated(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_selfUpdated(&mut self) -> Server_SelfUpdated {
        if self.has_selfUpdated() {
            match self.message.take() {
                ::std::option::Option::Some(Server_oneof_message::selfUpdated(v)) => v,
                _ => panic!(),
            }
        } else {
            Server_SelfUpdated::new()
        }
    }

    // .Server.PlayerEntered playerEntered = 4;


    pub fn get_playerEntered(&self) -> &Server_PlayerEntered {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerEntered(ref v)) => v,
            _ => <Server_PlayerEntered as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_playerEntered(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_playerEntered(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerEntered(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_playerEntered(&mut self, v: Server_PlayerEntered) {
        self.message = ::std::option::Option::Some(Server_oneof_message::playerEntered(v))
    }

    // Mutable pointer to the field.
    pub fn mut_playerEntered(&mut self) -> &mut Server_PlayerEntered {
        if let ::std::option::Option::Some(Server_oneof_message::playerEntered(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Server_oneof_message::playerEntered(Server_PlayerEntered::new()));
        }
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerEntered(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_playerEntered(&mut self) -> Server_PlayerEntered {
        if self.has_playerEntered() {
            match self.message.take() {
                ::std::option::Option::Some(Server_oneof_message::playerEntered(v)) => v,
                _ => panic!(),
            }
        } else {
            Server_PlayerEntered::new()
        }
    }

    // .Server.PlayerLeft playerLeft = 5;


    pub fn get_playerLeft(&self) -> &Server_PlayerLeft {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerLeft(ref v)) => v,
            _ => <Server_PlayerLeft as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_playerLeft(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_playerLeft(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerLeft(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_playerLeft(&mut self, v: Server_PlayerLeft) {
        self.message = ::std::option::Option::Some(Server_oneof_message::playerLeft(v))
    }

    // Mutable pointer to the field.
    pub fn mut_playerLeft(&mut self) -> &mut Server_PlayerLeft {
        if let ::std::option::Option::Some(Server_oneof_message::playerLeft(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Server_oneof_message::playerLeft(Server_PlayerLeft::new()));
        }
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::playerLeft(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_playerLeft(&mut self) -> Server_PlayerLeft {
        if self.has_playerLeft() {
            match self.message.take() {
                ::std::option::Option::Some(Server_oneof_message::playerLeft(v)) => v,
                _ => panic!(),
            }
        } else {
            Server_PlayerLeft::new()
        }
    }

    // .Server.GameDeclined gameDeclined = 6;


    pub fn get_gameDeclined(&self) -> &Server_GameDeclined {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::gameDeclined(ref v)) => v,
            _ => <Server_GameDeclined as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_gameDeclined(&mut self) {
        self.message = ::std::option::Option::None;
    }

    pub fn has_gameDeclined(&self) -> bool {
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::gameDeclined(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_gameDeclined(&mut self, v: Server_GameDeclined) {
        self.message = ::std::option::Option::Some(Server_oneof_message::gameDeclined(v))
    }

    // Mutable pointer to the field.
    pub fn mut_gameDeclined(&mut self) -> &mut Server_GameDeclined {
        if let ::std::option::Option::Some(Server_oneof_message::gameDeclined(_)) = self.message {
        } else {
            self.message = ::std::option::Option::Some(Server_oneof_message::gameDeclined(Server_GameDeclined::new()));
        }
        match self.message {
            ::std::option::Option::Some(Server_oneof_message::gameDeclined(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_gameDeclined(&mut self) -> Server_GameDeclined {
        if self.has_gameDeclined() {
            match self.message.take() {
                ::std::option::Option::Some(Server_oneof_message::gameDeclined(v)) => v,
                _ => panic!(),
            }
        } else {
            Server_GameDeclined::new()
        }
    }
}

impl ::protobuf::Message for Server {
    fn is_initialized(&self) -> bool {
        if let Some(Server_oneof_message::playerUpdated(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Server_oneof_message::gameUpdated(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Server_oneof_message::selfUpdated(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Server_oneof_message::playerEntered(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Server_oneof_message::playerLeft(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Server_oneof_message::gameDeclined(ref v)) = self.message {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Server_oneof_message::playerUpdated(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Server_oneof_message::gameUpdated(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Server_oneof_message::selfUpdated(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Server_oneof_message::playerEntered(is.read_message()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Server_oneof_message::playerLeft(is.read_message()?));
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.message = ::std::option::Option::Some(Server_oneof_message::gameDeclined(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.message {
            match v {
                &Server_oneof_message::playerUpdated(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Server_oneof_message::gameUpdated(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Server_oneof_message::selfUpdated(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Server_oneof_message::playerEntered(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Server_oneof_message::playerLeft(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Server_oneof_message::gameDeclined(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.message {
            match v {
                &Server_oneof_message::playerUpdated(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Server_oneof_message::gameUpdated(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Server_oneof_message::selfUpdated(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Server_oneof_message::playerEntered(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Server_oneof_message::playerLeft(ref v) => {
                    os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Server_oneof_message::gameDeclined(ref v) => {
                    os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server {
        Server::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Server_PlayerUpdated>(
                "playerUpdated",
                Server::has_playerUpdated,
                Server::get_playerUpdated,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Server_GameUpdated>(
                "gameUpdated",
                Server::has_gameUpdated,
                Server::get_gameUpdated,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Server_SelfUpdated>(
                "selfUpdated",
                Server::has_selfUpdated,
                Server::get_selfUpdated,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Server_PlayerEntered>(
                "playerEntered",
                Server::has_playerEntered,
                Server::get_playerEntered,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Server_PlayerLeft>(
                "playerLeft",
                Server::has_playerLeft,
                Server::get_playerLeft,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Server_GameDeclined>(
                "gameDeclined",
                Server::has_gameDeclined,
                Server::get_gameDeclined,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server>(
                "Server",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server {
        static instance: ::protobuf::rt::LazyV2<Server> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server::new)
    }
}

impl ::protobuf::Clear for Server {
    fn clear(&mut self) {
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.message = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server_PlayerUpdated {
    // message fields
    pub player: ::protobuf::SingularPtrField<super::player::Player>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server_PlayerUpdated {
    fn default() -> &'a Server_PlayerUpdated {
        <Server_PlayerUpdated as ::protobuf::Message>::default_instance()
    }
}

impl Server_PlayerUpdated {
    pub fn new() -> Server_PlayerUpdated {
        ::std::default::Default::default()
    }

    // .Player player = 1;


    pub fn get_player(&self) -> &super::player::Player {
        self.player.as_ref().unwrap_or_else(|| <super::player::Player as ::protobuf::Message>::default_instance())
    }
    pub fn clear_player(&mut self) {
        self.player.clear();
    }

    pub fn has_player(&self) -> bool {
        self.player.is_some()
    }

    // Param is passed by value, moved
    pub fn set_player(&mut self, v: super::player::Player) {
        self.player = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_player(&mut self) -> &mut super::player::Player {
        if self.player.is_none() {
            self.player.set_default();
        }
        self.player.as_mut().unwrap()
    }

    // Take field
    pub fn take_player(&mut self) -> super::player::Player {
        self.player.take().unwrap_or_else(|| super::player::Player::new())
    }
}

impl ::protobuf::Message for Server_PlayerUpdated {
    fn is_initialized(&self) -> bool {
        for v in &self.player {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.player)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.player.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.player.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server_PlayerUpdated {
        Server_PlayerUpdated::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::player::Player>>(
                "player",
                |m: &Server_PlayerUpdated| { &m.player },
                |m: &mut Server_PlayerUpdated| { &mut m.player },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server_PlayerUpdated>(
                "Server.PlayerUpdated",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server_PlayerUpdated {
        static instance: ::protobuf::rt::LazyV2<Server_PlayerUpdated> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server_PlayerUpdated::new)
    }
}

impl ::protobuf::Clear for Server_PlayerUpdated {
    fn clear(&mut self) {
        self.player.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server_PlayerUpdated {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server_PlayerUpdated {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server_SelfUpdated {
    // message fields
    pub player: ::protobuf::SingularPtrField<super::player::OwnPlayer>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server_SelfUpdated {
    fn default() -> &'a Server_SelfUpdated {
        <Server_SelfUpdated as ::protobuf::Message>::default_instance()
    }
}

impl Server_SelfUpdated {
    pub fn new() -> Server_SelfUpdated {
        ::std::default::Default::default()
    }

    // .OwnPlayer player = 1;


    pub fn get_player(&self) -> &super::player::OwnPlayer {
        self.player.as_ref().unwrap_or_else(|| <super::player::OwnPlayer as ::protobuf::Message>::default_instance())
    }
    pub fn clear_player(&mut self) {
        self.player.clear();
    }

    pub fn has_player(&self) -> bool {
        self.player.is_some()
    }

    // Param is passed by value, moved
    pub fn set_player(&mut self, v: super::player::OwnPlayer) {
        self.player = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_player(&mut self) -> &mut super::player::OwnPlayer {
        if self.player.is_none() {
            self.player.set_default();
        }
        self.player.as_mut().unwrap()
    }

    // Take field
    pub fn take_player(&mut self) -> super::player::OwnPlayer {
        self.player.take().unwrap_or_else(|| super::player::OwnPlayer::new())
    }
}

impl ::protobuf::Message for Server_SelfUpdated {
    fn is_initialized(&self) -> bool {
        for v in &self.player {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.player)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.player.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.player.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server_SelfUpdated {
        Server_SelfUpdated::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::player::OwnPlayer>>(
                "player",
                |m: &Server_SelfUpdated| { &m.player },
                |m: &mut Server_SelfUpdated| { &mut m.player },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server_SelfUpdated>(
                "Server.SelfUpdated",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server_SelfUpdated {
        static instance: ::protobuf::rt::LazyV2<Server_SelfUpdated> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server_SelfUpdated::new)
    }
}

impl ::protobuf::Clear for Server_SelfUpdated {
    fn clear(&mut self) {
        self.player.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server_SelfUpdated {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server_SelfUpdated {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server_GameUpdated {
    // message fields
    pub game: ::protobuf::SingularPtrField<super::game::Game>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server_GameUpdated {
    fn default() -> &'a Server_GameUpdated {
        <Server_GameUpdated as ::protobuf::Message>::default_instance()
    }
}

impl Server_GameUpdated {
    pub fn new() -> Server_GameUpdated {
        ::std::default::Default::default()
    }

    // .Game game = 1;


    pub fn get_game(&self) -> &super::game::Game {
        self.game.as_ref().unwrap_or_else(|| <super::game::Game as ::protobuf::Message>::default_instance())
    }
    pub fn clear_game(&mut self) {
        self.game.clear();
    }

    pub fn has_game(&self) -> bool {
        self.game.is_some()
    }

    // Param is passed by value, moved
    pub fn set_game(&mut self, v: super::game::Game) {
        self.game = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_game(&mut self) -> &mut super::game::Game {
        if self.game.is_none() {
            self.game.set_default();
        }
        self.game.as_mut().unwrap()
    }

    // Take field
    pub fn take_game(&mut self) -> super::game::Game {
        self.game.take().unwrap_or_else(|| super::game::Game::new())
    }
}

impl ::protobuf::Message for Server_GameUpdated {
    fn is_initialized(&self) -> bool {
        for v in &self.game {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.game)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.game.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.game.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server_GameUpdated {
        Server_GameUpdated::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::game::Game>>(
                "game",
                |m: &Server_GameUpdated| { &m.game },
                |m: &mut Server_GameUpdated| { &mut m.game },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server_GameUpdated>(
                "Server.GameUpdated",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server_GameUpdated {
        static instance: ::protobuf::rt::LazyV2<Server_GameUpdated> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server_GameUpdated::new)
    }
}

impl ::protobuf::Clear for Server_GameUpdated {
    fn clear(&mut self) {
        self.game.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server_GameUpdated {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server_GameUpdated {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server_PlayerEntered {
    // message fields
    pub player: ::protobuf::SingularPtrField<super::player::Player>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server_PlayerEntered {
    fn default() -> &'a Server_PlayerEntered {
        <Server_PlayerEntered as ::protobuf::Message>::default_instance()
    }
}

impl Server_PlayerEntered {
    pub fn new() -> Server_PlayerEntered {
        ::std::default::Default::default()
    }

    // .Player player = 1;


    pub fn get_player(&self) -> &super::player::Player {
        self.player.as_ref().unwrap_or_else(|| <super::player::Player as ::protobuf::Message>::default_instance())
    }
    pub fn clear_player(&mut self) {
        self.player.clear();
    }

    pub fn has_player(&self) -> bool {
        self.player.is_some()
    }

    // Param is passed by value, moved
    pub fn set_player(&mut self, v: super::player::Player) {
        self.player = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_player(&mut self) -> &mut super::player::Player {
        if self.player.is_none() {
            self.player.set_default();
        }
        self.player.as_mut().unwrap()
    }

    // Take field
    pub fn take_player(&mut self) -> super::player::Player {
        self.player.take().unwrap_or_else(|| super::player::Player::new())
    }
}

impl ::protobuf::Message for Server_PlayerEntered {
    fn is_initialized(&self) -> bool {
        for v in &self.player {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.player)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.player.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.player.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server_PlayerEntered {
        Server_PlayerEntered::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::player::Player>>(
                "player",
                |m: &Server_PlayerEntered| { &m.player },
                |m: &mut Server_PlayerEntered| { &mut m.player },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server_PlayerEntered>(
                "Server.PlayerEntered",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server_PlayerEntered {
        static instance: ::protobuf::rt::LazyV2<Server_PlayerEntered> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server_PlayerEntered::new)
    }
}

impl ::protobuf::Clear for Server_PlayerEntered {
    fn clear(&mut self) {
        self.player.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server_PlayerEntered {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server_PlayerEntered {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server_PlayerLeft {
    // message fields
    pub player_id: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server_PlayerLeft {
    fn default() -> &'a Server_PlayerLeft {
        <Server_PlayerLeft as ::protobuf::Message>::default_instance()
    }
}

impl Server_PlayerLeft {
    pub fn new() -> Server_PlayerLeft {
        ::std::default::Default::default()
    }

    // string player_id = 1;


    pub fn get_player_id(&self) -> &str {
        &self.player_id
    }
    pub fn clear_player_id(&mut self) {
        self.player_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_player_id(&mut self, v: ::std::string::String) {
        self.player_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_player_id(&mut self) -> &mut ::std::string::String {
        &mut self.player_id
    }

    // Take field
    pub fn take_player_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.player_id, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Server_PlayerLeft {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.player_id)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.player_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.player_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.player_id.is_empty() {
            os.write_string(1, &self.player_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server_PlayerLeft {
        Server_PlayerLeft::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "player_id",
                |m: &Server_PlayerLeft| { &m.player_id },
                |m: &mut Server_PlayerLeft| { &mut m.player_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server_PlayerLeft>(
                "Server.PlayerLeft",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server_PlayerLeft {
        static instance: ::protobuf::rt::LazyV2<Server_PlayerLeft> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server_PlayerLeft::new)
    }
}

impl ::protobuf::Clear for Server_PlayerLeft {
    fn clear(&mut self) {
        self.player_id.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server_PlayerLeft {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server_PlayerLeft {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Server_GameDeclined {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Server_GameDeclined {
    fn default() -> &'a Server_GameDeclined {
        <Server_GameDeclined as ::protobuf::Message>::default_instance()
    }
}

impl Server_GameDeclined {
    pub fn new() -> Server_GameDeclined {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Server_GameDeclined {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Server_GameDeclined {
        Server_GameDeclined::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Server_GameDeclined>(
                "Server.GameDeclined",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Server_GameDeclined {
        static instance: ::protobuf::rt::LazyV2<Server_GameDeclined> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Server_GameDeclined::new)
    }
}

impl ::protobuf::Clear for Server_GameDeclined {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Server_GameDeclined {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Server_GameDeclined {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rmessage.proto\x1a\x0cplayer.proto\x1a\ngame.proto\"\x9d\x02\n\x06Cli\
    ent\x12=\n\rauthConfirmed\x18\x01\x20\x01(\x0b2\x15.Client.AuthConfirmed\
    H\0R\rauthConfirmed\x127\n\x0bnameUpdated\x18\x02\x20\x01(\x0b2\x13.Clie\
    nt.NameUpdatedH\0R\x0bnameUpdated\x127\n\x0bgameStarted\x18\x03\x20\x01(\
    \x0b2\x13.Client.GameStartedH\0R\x0bgameStarted\x1a%\n\rAuthConfirmed\
    \x12\x14\n\x05token\x18\x01\x20\x01(\tR\x05token\x1a!\n\x0bNameUpdated\
    \x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x1a\r\n\x0bGameStartedB\t\
    \n\x07message\"\xf1\x04\n\x06Server\x12=\n\rplayerUpdated\x18\x01\x20\
    \x01(\x0b2\x15.Server.PlayerUpdatedH\0R\rplayerUpdated\x127\n\x0bgameUpd\
    ated\x18\x02\x20\x01(\x0b2\x13.Server.GameUpdatedH\0R\x0bgameUpdated\x12\
    7\n\x0bselfUpdated\x18\x03\x20\x01(\x0b2\x13.Server.SelfUpdatedH\0R\x0bs\
    elfUpdated\x12=\n\rplayerEntered\x18\x04\x20\x01(\x0b2\x15.Server.Player\
    EnteredH\0R\rplayerEntered\x124\n\nplayerLeft\x18\x05\x20\x01(\x0b2\x12.\
    Server.PlayerLeftH\0R\nplayerLeft\x12:\n\x0cgameDeclined\x18\x06\x20\x01\
    (\x0b2\x14.Server.GameDeclinedH\0R\x0cgameDeclined\x1a0\n\rPlayerUpdated\
    \x12\x1f\n\x06player\x18\x01\x20\x01(\x0b2\x07.PlayerR\x06player\x1a1\n\
    \x0bSelfUpdated\x12\"\n\x06player\x18\x01\x20\x01(\x0b2\n.OwnPlayerR\x06\
    player\x1a(\n\x0bGameUpdated\x12\x19\n\x04game\x18\x01\x20\x01(\x0b2\x05\
    .GameR\x04game\x1a0\n\rPlayerEntered\x12\x1f\n\x06player\x18\x01\x20\x01\
    (\x0b2\x07.PlayerR\x06player\x1a)\n\nPlayerLeft\x12\x1b\n\tplayer_id\x18\
    \x01\x20\x01(\tR\x08playerId\x1a\x0e\n\x0cGameDeclinedB\t\n\x07messageJ\
    \xab\n\n\x06\x12\x04\0\0!\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\t\n\x02\
    \x03\0\x12\x03\x02\0\x16\n\t\n\x02\x03\x01\x12\x03\x03\0\x14\n\n\n\x02\
    \x04\0\x12\x04\x05\0\x0f\x01\n\n\n\x03\x04\0\x01\x12\x03\x05\x08\x0e\n\
    \x0b\n\x04\x04\0\x03\0\x12\x03\x06\x02-\n\x0c\n\x05\x04\0\x03\0\x01\x12\
    \x03\x06\n\x17\n\r\n\x06\x04\0\x03\0\x02\0\x12\x03\x06\x1a+\n\x0e\n\x07\
    \x04\0\x03\0\x02\0\x05\x12\x03\x06\x1a\x20\n\x0e\n\x07\x04\0\x03\0\x02\0\
    \x01\x12\x03\x06!&\n\x0e\n\x07\x04\0\x03\0\x02\0\x03\x12\x03\x06)*\n\x0b\
    \n\x04\x04\0\x03\x01\x12\x03\x07\x02*\n\x0c\n\x05\x04\0\x03\x01\x01\x12\
    \x03\x07\n\x15\n\r\n\x06\x04\0\x03\x01\x02\0\x12\x03\x07\x18(\n\x0e\n\
    \x07\x04\0\x03\x01\x02\0\x05\x12\x03\x07\x18\x1e\n\x0e\n\x07\x04\0\x03\
    \x01\x02\0\x01\x12\x03\x07\x1f#\n\x0e\n\x07\x04\0\x03\x01\x02\0\x03\x12\
    \x03\x07&'\n\x0b\n\x04\x04\0\x03\x02\x12\x03\x08\x02\x18\n\x0c\n\x05\x04\
    \0\x03\x02\x01\x12\x03\x08\n\x15\n\x0c\n\x04\x04\0\x08\0\x12\x04\n\x02\
    \x0e\x03\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\n\x08\x0f\n\x0b\n\x04\x04\0\
    \x02\0\x12\x03\x0b\x04$\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\x0b\x04\x11\
    \n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x0b\x12\x1f\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03\x0b\"#\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x0c\x04\x20\n\x0c\
    \n\x05\x04\0\x02\x01\x06\x12\x03\x0c\x04\x0f\n\x0c\n\x05\x04\0\x02\x01\
    \x01\x12\x03\x0c\x10\x1b\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x0c\x1e\
    \x1f\n\x0b\n\x04\x04\0\x02\x02\x12\x03\r\x04\x20\n\x0c\n\x05\x04\0\x02\
    \x02\x06\x12\x03\r\x04\x0f\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\r\x10\
    \x1b\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\r\x1e\x1f\n\n\n\x02\x04\x01\
    \x12\x04\x11\0!\x01\n\n\n\x03\x04\x01\x01\x12\x03\x11\x08\x0e\n\x0b\n\
    \x04\x04\x01\x03\0\x12\x03\x12\x02.\n\x0c\n\x05\x04\x01\x03\0\x01\x12\
    \x03\x12\n\x17\n\r\n\x06\x04\x01\x03\0\x02\0\x12\x03\x12\x1a,\n\x0e\n\
    \x07\x04\x01\x03\0\x02\0\x06\x12\x03\x12\x1a\x20\n\x0e\n\x07\x04\x01\x03\
    \0\x02\0\x01\x12\x03\x12!'\n\x0e\n\x07\x04\x01\x03\0\x02\0\x03\x12\x03\
    \x12*+\n\x0b\n\x04\x04\x01\x03\x01\x12\x03\x13\x02/\n\x0c\n\x05\x04\x01\
    \x03\x01\x01\x12\x03\x13\n\x15\n\r\n\x06\x04\x01\x03\x01\x02\0\x12\x03\
    \x13\x18-\n\x0e\n\x07\x04\x01\x03\x01\x02\0\x06\x12\x03\x13\x18!\n\x0e\n\
    \x07\x04\x01\x03\x01\x02\0\x01\x12\x03\x13\"(\n\x0e\n\x07\x04\x01\x03\
    \x01\x02\0\x03\x12\x03\x13+,\n\x0b\n\x04\x04\x01\x03\x02\x12\x03\x14\x02\
    (\n\x0c\n\x05\x04\x01\x03\x02\x01\x12\x03\x14\n\x15\n\r\n\x06\x04\x01\
    \x03\x02\x02\0\x12\x03\x14\x18&\n\x0e\n\x07\x04\x01\x03\x02\x02\0\x06\
    \x12\x03\x14\x18\x1c\n\x0e\n\x07\x04\x01\x03\x02\x02\0\x01\x12\x03\x14\
    \x1d!\n\x0e\n\x07\x04\x01\x03\x02\x02\0\x03\x12\x03\x14$%\n\x0b\n\x04\
    \x04\x01\x03\x03\x12\x03\x15\x02.\n\x0c\n\x05\x04\x01\x03\x03\x01\x12\
    \x03\x15\n\x17\n\r\n\x06\x04\x01\x03\x03\x02\0\x12\x03\x15\x1a,\n\x0e\n\
    \x07\x04\x01\x03\x03\x02\0\x06\x12\x03\x15\x1a\x20\n\x0e\n\x07\x04\x01\
    \x03\x03\x02\0\x01\x12\x03\x15!'\n\x0e\n\x07\x04\x01\x03\x03\x02\0\x03\
    \x12\x03\x15*+\n\x0b\n\x04\x04\x01\x03\x04\x12\x03\x16\x02.\n\x0c\n\x05\
    \x04\x01\x03\x04\x01\x12\x03\x16\n\x14\n\r\n\x06\x04\x01\x03\x04\x02\0\
    \x12\x03\x16\x17,\n\x0e\n\x07\x04\x01\x03\x04\x02\0\x05\x12\x03\x16\x17\
    \x1d\n\x0e\n\x07\x04\x01\x03\x04\x02\0\x01\x12\x03\x16\x1e'\n\x0e\n\x07\
    \x04\x01\x03\x04\x02\0\x03\x12\x03\x16*+\n\x0b\n\x04\x04\x01\x03\x05\x12\
    \x03\x17\x02\x19\n\x0c\n\x05\x04\x01\x03\x05\x01\x12\x03\x17\n\x16\n\x0c\
    \n\x04\x04\x01\x08\0\x12\x04\x19\x02\x20\x03\n\x0c\n\x05\x04\x01\x08\0\
    \x01\x12\x03\x19\x08\x0f\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x1a\x04$\n\
    \x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x1a\x04\x11\n\x0c\n\x05\x04\x01\x02\
    \0\x01\x12\x03\x1a\x12\x1f\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x1a\"#\
    \n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x1b\x04\x20\n\x0c\n\x05\x04\x01\x02\
    \x01\x06\x12\x03\x1b\x04\x0f\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x1b\
    \x10\x1b\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x1b\x1e\x1f\n\x0b\n\x04\
    \x04\x01\x02\x02\x12\x03\x1c\x04\x20\n\x0c\n\x05\x04\x01\x02\x02\x06\x12\
    \x03\x1c\x04\x0f\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x1c\x10\x1b\n\
    \x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x1c\x1e\x1f\n\x0b\n\x04\x04\x01\
    \x02\x03\x12\x03\x1d\x04$\n\x0c\n\x05\x04\x01\x02\x03\x06\x12\x03\x1d\
    \x04\x11\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\x1d\x12\x1f\n\x0c\n\x05\
    \x04\x01\x02\x03\x03\x12\x03\x1d\"#\n\x0b\n\x04\x04\x01\x02\x04\x12\x03\
    \x1e\x04\x1e\n\x0c\n\x05\x04\x01\x02\x04\x06\x12\x03\x1e\x04\x0e\n\x0c\n\
    \x05\x04\x01\x02\x04\x01\x12\x03\x1e\x0f\x19\n\x0c\n\x05\x04\x01\x02\x04\
    \x03\x12\x03\x1e\x1c\x1d\n\x0b\n\x04\x04\x01\x02\x05\x12\x03\x1f\x04\"\n\
    \x0c\n\x05\x04\x01\x02\x05\x06\x12\x03\x1f\x04\x10\n\x0c\n\x05\x04\x01\
    \x02\x05\x01\x12\x03\x1f\x11\x1d\n\x0c\n\x05\x04\x01\x02\x05\x03\x12\x03\
    \x1f\x20!b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
